##
# log4j2-local.yml
# log4j2 설정 파일 : 로컬(local)
##

Configuration:
    # 일반 로그 출력 레벨 설정
    # trace | debug | info | warn | error | fatal
    status: info

    Properties:
        Property:
            - name: log-path
              value: "log"
            - name: log-format
              value: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} %c{1}.%M(%L) - %msg%n"

    Appenders:
        Console:
            - name: Console_Appender
              target: SYSTEM_OUT
              PatternLayout:
                  pattern: ${log-format}
        RollingFile:
            - name: RollingFile_INFO_Appender
              fileName: ${log-path}/dreamdiary.log
              filePattern: "${log-path}/archive/dreamdiary.log.%d{yyyy-MM-dd}.gz"
              PatternLayout:
                  pattern: ${log-format}
              Policies:
                  SizeBasedTriggeringPolicy:
                      size: 1GB
                  TimeBasedTriggeringPolicy:
                      interval: 1
                      modulate: true
            # WARN↑ 이상 로그 파일 별도 분리
            - name: RollingFile_WARN_Appender
              fileName: ${log-path}/dreamdiary-WARN.log
              filePattern: "${log-path}/archive/dreamdiary-WARN.log.%d{yyyy-MM-dd}.gz"
              PatternLayout:
                  pattern: ${log-format}
              Policies:
                  SizeBasedTriggeringPolicy:
                      size: 1GB
                  TimeBasedTriggeringPolicy:
                      interval: 1
                      modulate: true

    Loggers:
        Root:
            level: info
            AppenderRef:
              - ref: Console_Appender
        Logger:
          - name: dreamdiary.nicheblog.io
            additivity: false
            level: info
            AppenderRef:
              - ref: Console_Appender