##
# application-local.yml
# 로컬(local) 프로필용 설정 파일
##

# 로컬 포트 = 18081
server:
    domain: ${SERVER_DOMAIN:localhost}
    port: ${SERVER_PORT:18081}

spring:
    devtools:
        add-properties: true
        livereload:
            enabled: true
            port: 18089
        remote:
            restart:
                enabled: false
        restart:
            enabled: true

    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MariaDBDialect
        properties:
            hibernate:
                database: mysql
                dialect: org.hibernate.dialect.MariaDBDialect

    sql:
        init:
            # mode: always / embedded / never
            mode: never
            platform: mariadb
            continue-on-error: true

    redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        password: ${REDIS_PASSWORD}

    kafka:
        bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
        consumer:
            group-id: dreamdiary
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

    elasticsearch:
        username: ${ELASTIC_USERNAME}
        password: ${ELASTIC_PASSWORD}
        uris: ${ELASTIC_URIS}

#jandi messenger properties
api:
    jandi:
        teamId: ${JANDI_TEAM_ID}
        topics:
            - name: NOTICE
              id:  ${JANDI_TOPIC_NOTICE}
            - name: SCHDUL
              id: ${JANDI_TOPIC_SCHDUL}
            - name: TEST
              id: ${TEST}