#application-local.yml
#운영(prod) 프로필용 설정 파일

server:
    port: ${SERVER_PORT:8999}

logging:
    config: classpath:log4j2-prod.yml

spring:
    servlet:
        multipart:
            location: ${FILE_UPLOAD_LOCATION}
    freemarker:
        cache: ${FREEMARKER_CACHE:true}
    datasource:
        primary:
            driver-class-name: org.mariadb.jdbc.Driver
            jdbc-url: ${JDBC_URL}
            username: ${JDBC_USERNAME}
            password: ${JDBC_PASSWORD}

    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MariaDBDialect
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true
                generate-ddl: true

    sql:
        init:
            # mode: always / embedded / never
            mode: never
            platform: mariadb
            continue-on-error: true

    redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        password: ${REDIS_PASSWORD}

    kafka:
        bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
        consumer:
            group-id: dreamdiary
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

    elasticsearch:
        username: ${ELASTIC_USERNAME}
        password: ${ELASTIC_PASSWORD}
        uris: ${ELASTIC_URIS}

api:
    jandi:
        teamId: ${JANDI_TEAM_ID}
        topics:
            - name: NOTICE
              id:  ${JANDI_TOPIC_NOTICE}
            - name: SCHDUL
              id: ${JANDI_TOPIC_SCHDUL}
            - name: TEST
              id: ${TEST}