-- 쿼리 줄바꿈 안됨. 무조건 한 줄에 한 쿼리 단위로 실행된다.

-- 필수 :: 로그인 설정 정보 추가
REPLACE INTO LGN_POLICY (LGN_POLICY_NO, LGN_TRY_LMT, PW_CHG_DY, LGN_LOCK_DY, PW_FOR_RESET) VALUES ('1', '5', '90', '90', '123qwe!QA');

-- -----------------------


-- -----------------------

-- 필수 :: 시퀀스 정보 추가
REPLACE INTO CMM_SEQ(SEQ_ID, SEQ_NM, SEQ_VAL) VALUES (1, 'POST_NO', 1);
REPLACE INTO CMM_SEQ(SEQ_ID, SEQ_NM, SEQ_VAL) VALUES (2, 'EXPTR_INDVD_NO', 1);
REPLACE INTO CMM_SEQ(SEQ_ID, SEQ_NM, SEQ_VAL) VALUES (3, 'NOTICE_NO', 1);
REPLACE INTO CMM_SEQ(SEQ_ID, SEQ_NM, SEQ_VAL) VALUES (4, 'VCATN_PAPR_NO', 1);
REPLACE INTO CMM_SEQ(SEQ_ID, SEQ_NM, SEQ_VAL) VALUES (5, 'EXPTR_REQST_NO', 1);
REPLACE INTO CMM_SEQ(SEQ_ID, SEQ_NM, SEQ_VAL) VALUES (6, 'FLSYS_META_NO', 1);