-- 사용자 관련 구조 테이블 생성 쿼리 정보를 입력한다.
-- "JPA CASCADE INSERT에서는 먼저 INSERT 후 나중에 FK값을 업데이트하게 되므로 FK가 NOT_NULL이면 에러가 발생한다."
-- (=> JPA에서 다른 테이블과 연관성을 갖는 컬럼은 반드시 NULL을 허용해야 한다!) (NOT NULL이면 안된다)
-- @database : mariadb
-- @author : nichefish

-- 사용자 계정 정보
CREATE TABLE IF NOT EXISTS USER (
    USER_NO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(20),
    USER_PW VARCHAR(64),
    USER_NM VARCHAR(50),
    NICK_NM VARCHAR(50),
    AUTH_CD VARCHAR(10),
    PROFL_IMG_URL VARCHAR(256),
    USER_INFO_NO INT,       /* 세부정보 위임 */
    LOCK_YN CHAR(1) DEFAULT 'N',
    ACS_IP_YN CHAR(1) DEFAULT 'N',
    LST_LGN_DT DATETIME,
    LGN_FAIL_CNT INT DEFAULT 0,
    PW_CHG_DT DATETIME,
    RETIRE_YN CHAR(1) DEFAULT 'N',
    USER_DC VARCHAR(4000),
    NEEDS_PW_RESET CHAR(1) DEFAULT 'N',
    DORMANT_BYPASS_YN CHAR(1) DEFAULT 'N',
    REQST_YN CHAR(1) DEFAULT 'N',
    CF_YN CHAR(1) DEFAULT 'N',
    -- ATCH_FILE
    ATCH_FILE_NO INT,
    -- AUDIT
    REGSTR_ID VARCHAR(20) COMMENT '등록자ID',
    REG_DT DATETIME DEFAULT NOW() COMMENT '등록일시',
    MDFUSR_ID VARCHAR(20) COMMENT '수정자ID',
    MDF_DT DATETIME COMMENT '수정일시',
    DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
) COMMENT = '사용자 계정';

-- 사용자 계정 정보 :: 접속 IP
CREATE TABLE IF NOT EXISTS USER_ACS_IP (
    USER_ACS_IP_NO INT AUTO_INCREMENT PRIMARY KEY,
    USER_NO INT,
    ACS_IP VARCHAR(20),
    -- AUDIT
    DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    -- CONSTRAINT
    FOREIGN KEY(USER_NO) REFERENCES USER (USER_NO)
) COMMENT = '사용자 접속IP';

-- 사용자 정보
-- (인사정보로 확장??)
CREATE TABLE IF NOT EXISTS USER_INFO (
    USER_INFO_NO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_NM VARCHAR(50),
    CTTPC VARCHAR(20),
    EMAIL VARCHAR(40),
    CMPY_CD VARCHAR(30),
    TEAM_CD VARCHAR(30),
    EMPLYM_CD VARCHAR(30),
    ECNY_DT DATE,
    RETIRE_YN CHAR(1) DEFAULT 'N',
    RETIRE_DT DATETIME,
    JOB_TITLE_CD VARCHAR(30),
    APNTC_YN CHAR(1) DEFAULT 'N',
    BRTHDY DATE,
    LUNAR_YN CHAR(1) DEFAULT 'N',
    ACNT_BANK VARCHAR(50),
    ACNT_NO VARCHAR(50),
    USER_DC VARCHAR(2000),
    -- AUDIT
    REGSTR_ID VARCHAR(20) COMMENT '등록자ID',
    REG_DT DATETIME DEFAULT NOW() COMMENT '등록일시',
    MDFUSR_ID VARCHAR(20) COMMENT '수정자ID',
    MDF_DT DATETIME COMMENT '수정일시',
    DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
) COMMENT = '사용자 정보';

-- 사용자 권한
CREATE TABLE USER_ROLE (
    AUTH_CD VARCHAR(50) PRIMARY KEY,
    AUTH_NM VARCHAR(50),
    AUTH_LEVEL INT,
    TOP_AUTH_CD VARCHAR(50),
    SORT_ORDR INT DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    -- AUDIT
    DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
) COMMENT = '사용자 권한';

-- 사용자 정보 - 팀
CREATE TABLE IF NOT EXISTS USER_INFO_TEAM (
    USER_INFO_TEAM_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_INFO_NO INT,
    TEAM_CD VARCHAR(30),
    -- AUDIT
    DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
);

-- 사용자 정보 - 기타항목
CREATE TABLE IF NOT EXISTS USER_INFO_ITEM (
    USER_INFO_ITEM_NO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_INFO_NO INT,
    ITEM_NM VARCHAR(100),
    ITEM_CN VARCHAR(200),
    ITEM_DC VARCHAR(2000),
    SORT_ORDR INT DEFAULT 0 COMMENT '정렬 순서',
    -- AUDIT
    DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
);
