-- 공통 구조 테이블 생성 쿼리 정보를 입력한다.
-- "JPA CASCADE INSERT에서는 먼저 INSERT 후 나중에 FK값을 업데이트하게 되므로 FK가 NOT_NULL이면 에러가 발생한다."
-- (=> JPA에서 다른 테이블과 연관성을 갖는 컬럼은 반드시 NULL을 허용해야 한다!) (NOT NULL이면 안된다)
-- @database : mariadb
-- @author : nichefish

-- ---------- --

-- 복합키 요소에 대한 시퀀스 테이블
-- AUTO_INCREMENT가 먹지 않는 복합키 요소에 대하여 사용
CREATE TABLE IF NOT EXISTS CMM_SEQ (
    SEQ_ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '시퀀스ID',
    SEQ_NM VARCHAR(30) COMMENT '시퀀스 이름',
    SEQ_VAL INT NOT NULL DEFAULT 0 COMMENT '시퀀스 값'
) COMMENT = '복합키 시퀀스';

-- ---------- --

-- 분류 코드
CREATE TABLE IF NOT EXISTS CMM_CL_CD  (
    CL_CD VARCHAR(20) NOT NULL PRIMARY KEY COMMENT '분류 코드',
    CL_CD_NM VARCHAR(40) COMMENT '분류 코드명',
    CL_CD_DC VARCHAR(400) COMMENT '분류 코드 설명',
    -- MANAGE
    SORT_ORDR INT DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    -- AUDIT
    REGSTR_ID VARCHAR(20) COMMENT '등록자ID',
    REG_DT DATETIME DEFAULT NOW() COMMENT '등록일시',
    MDFUSR_ID VARCHAR(20) COMMENT '수정자ID',
    MDF_DT DATETIME COMMENT '수정일시',
    DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
) COMMENT = '분류 코드';

-- 상세 코드
CREATE TABLE IF NOT EXISTS CMM_DTL_CD (
    CL_CD VARCHAR(20) COMMENT '분류 코드',
    DTL_CD VARCHAR(30) COMMENT '상세 코드',
    DTL_CD_NM VARCHAR(40) COMMENT '상세 코드명',
    DTL_CD_DC VARCHAR(400) COMMENT '상세 코드 설명',
    -- MANAGE
    SORT_ORDR INT DEFAULT 0 COMMENT '정렬 순서',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    -- AUDIT
    REGSTR_ID VARCHAR(20) COMMENT '등록자ID',
    REG_DT DATETIME DEFAULT NOW() COMMENT '등록일시',
    MDFUSR_ID VARCHAR(20) COMMENT '수정자ID',
    MDF_DT DATETIME COMMENT '수정일시',
    DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    -- CONSTRAINT
    PRIMARY KEY (CL_CD, DTL_CD)
) COMMENT = '상세 코드';

-- ---------- --

-- 로그인 정책
CREATE TABLE IF NOT EXISTS LGN_POLICY (
    LGN_POLICY_NO INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '로그인 정책 번호',
    LGN_TRY_LMT INT COMMENT '로그인 정책 번호',
    PW_CHG_DY INT,
    LGN_LOCK_DY INT,
    PW_FOR_RESET VARCHAR(20),
    -- AUDIT
    REGSTR_ID VARCHAR(20) COMMENT '등록자ID',
    REG_DT DATETIME DEFAULT NOW() COMMENT '등록일시',
    MDFUSR_ID VARCHAR(20) COMMENT '수정자ID',
    MDF_DT DATETIME COMMENT '수정일시',
    DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
) COMMENT = '로그인 정책';

-- ---------- --

-- 첨부파일
CREATE TABLE IF NOT EXISTS ATCH_FILE (
    ATCH_FILE_NO BIGINT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '첨부파일 번호',
    DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
) COMMENT = '첨부파일';

-- 첨부파일 상세
CREATE TABLE IF NOT EXISTS ATCH_FILE_DTL (
    ATCH_FILE_DTL_NO INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '첨부파일 상세 번호',
    ATCH_FILE_NO BIGINT COMMENT '첨부파일 번호',
    FILE_SN INT COMMENT '파일 순번',
    ORGN_FILE_NM VARCHAR(200) COMMENT '원본파일명',
    STRE_FILE_NM VARCHAR(200) COMMENT '저장파일명',
    FILE_EXTN VARCHAR(10) COMMENT '파일 확장자',
    FILE_STRE_PATH VARCHAR(200) COMMENT '파일 저장 경로',
    FILE_SIZE INT COMMENT '파일 크기(BYTE)',
    URL VARCHAR(500) COMMENT '파일 URL',
    DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    -- CONSTRAINT
    FOREIGN KEY(ATCH_FILE_NO) REFERENCES ATCH_FILE (ATCH_FILE_NO)
) COMMENT = '첨부파일 상세';

-- ---------- --

-- 활동 로그
CREATE TABLE IF NOT EXISTS LOG_ACTVTY (
    LOG_ACTVTY_NO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOG_TY_CD VARCHAR(50),
    LOG_DT DATETIME,
    LOG_USER_ID VARCHAR(20),
    --
    ACTVTY_CTGR_CD VARCHAR(50),
    ACTION_TY_CD VARCHAR(50),
    --
    URL VARCHAR(400),
    PARAM VARCHAR(500),
    CN VARCHAR(400),
    IP_ADDR VARCHAR(20),
    REFERER VARCHAR(1000),
    RSLT CHAR(1),
    RSLT_MSG VARCHAR(50),
    EXCEPTION_NM VARCHAR(100),
    EXCEPTION_MSG VARCHAR(4000)
) COMMENT = '활동 로그';

-- 활동 로그 URL-이름 매칭
CREATE TABLE IF NOT EXISTS LOG_ACTVTY_URL_NM (
    LOG_ACTVTY_URL_NM_NO INT AUTO_INCREMENT PRIMARY KEY,
    URL VARCHAR(200) UNIQUE,
    URL_NM VARCHAR(200),
    DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
) COMMENT = '활동 로그 URL명';

-- 시스템 로그
CREATE TABLE IF NOT EXISTS LOG_SYS (
    LOG_SYS_NO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOG_TY_CD VARCHAR(50),
    LOG_DT DATETIME,
    LOG_USER_ID VARCHAR(20),
    --
    ACTVTY_CTGR_CD VARCHAR(50),
    ACTION_TY_CD VARCHAR(50),
    --
    URL VARCHAR(400),
    CN VARCHAR(400),
    RSLT CHAR(1),
    RSLT_MSG VARCHAR(500),
    EXCEPTION_NM VARCHAR(100),
    EXCEPTION_MSG VARCHAR(4000)
) COMMENT = '시스템 로그';