#config/application.yml
#common config located outside .jar

#release date. should be changed manually for each deployment
release-date: 20240215

#AES128 secret key
aes128:
    secret-key: "0000000000000000"

spring:
    #( local // dev // stg // prod // test )
    profiles:
        active: dev

logging:
    level:
        #web: INFO
        org.hibernate.SQL: debug
        org.hibernate.type.descriptor.sql: trace