#config/application.yml
#common config located outside .jar

spring:
    #( local // dev // stg // prod // test )
    profiles:
        active: dev

    #release. should be changed manually for each deployment
    flyway:
        enabled: true   # Flyway 활성화
        target: 0.12.0_6  # V0.12.1까지만 적용하고 이후 버전은 실행 안 함
        release-date: 20250131

logging:
    level:
        web: INFO
        org.springframework: INFO