<#--
  -- 사이트 관리 화면
  -->
<#import "/layout/layout.ftlh" as layout >
<#import "/spring.ftl" as spring />


<script defer="defer" src="/static/node_modules/sass/sass.js"></script>

<@layout.layout>

<script>
    const Page = function() {
        return {
            init: function () {
                //
            },

        }
    }();
</script>

<!--begin::Card-->
<div class="card post">

</div>
<!--end::Card-->

</@layout.layout>